### ISSUE TITLE
Annotations AWS Loadbalancer

### ISSUE THREAD

**Issue by mgbarnech** [fiskaltrust/product-de-bring-your-own-datacenter#50]
In our BYODC Middleware configuration we have "TLS termination at the load balancer" (https://www.getambassador.io/docs/edge-stack/latest/topics/running/ambassador-with-aws/#tls-termination-at-the-load-balancer)
We need to add some annotations to the current chart, specifically to the ambassador service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: ambassador
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ACM_CERT_ARN}}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  ports:
  - name: HTTP
    port: 80
    targetPort: 8080
  - name: HTTPS
    port: 443
    targetPort: 8080
  selector:
    service: ambassador

```

do you have a recommendation to add these annotations or are you planning to include annotations in the following releases?

**Comment by volllly** [comment]
Hi @mgbarnech 

you can specify configuration values from the ambassador chart (https://github.com/emissary-ingress/emissary/tree/master/charts/emissary-ingress#configuration) to your `values.yaml` file under the ambassador key.

if you add the following to your `vaules.yaml` the annotations will be added to the ambassador loadbalancer

```yaml
ambassador:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ACM_CERT_ARN}}
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
```

**Comment by mgbarnech** [comment]
Hi @volllly 
Its works!.Thank you. 
I also added the ports settings. I write it down here in case it helps someone
```yaml
ambassador:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ACM_CERT_ARN}}
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    ports:
      - name: https
        port: 443
        targetPort: 8080
```
