### ISSUE TITLE
need to be able to extend env variables of main application pod

### ISSUE THREAD

**Issue by zeph** [fiskaltrust/product-de-bring-your-own-datacenter#57]
please extend this section of the `byodc` Deployment resource 
```yaml
          env:
            - name: Redis__ConnectionString
              value: {{ tpl .Values.byodc.config.redis.host . }}:{{ .Values.byodc.config.redis.port }}
            - name: Redis__Channel
              value: {{ .Values.byodc.config.redis.channel }}
              {{- with .Values.byodc.config.applicationInsights }}{{ if .instrumentationKey }}
            - name: ApplicationInsights__InstrumentationKey
              value: {{ .instrumentationKey }}
              {{- end }}{{ end }}
            - name: Logging__LogLevel__Default
              value: {{ .Values.byodc.config.logLevel }}
            - name: Helipad__BaseUrl
              value: {{ .Values.byodc.config.helipad.baseUrl }}
              {{- with .Values.byodc.proxy }}{{ range $key, $value := . }}{{if $value }}
            - name: {{ $key | upper }}_PROXY
              value: {{ $value | quote }}
              {{- end }}{{ end }}{{ end }}
```
            
with something like this

```yaml
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
```

as we need to inject env variable for the Datadog based telemetry

p.s. we attempted to use Kustomize, but we have other limitation for which we could not run a post-renderer

**Comment by volllly** [comment]
Hi @zeph,
we've released version `1.3.24` of the helm chart with your suggested functionality.

the config should look like this:
```yaml
byodc:
  config:
    ...
    env:
    - name: DD_AGENT_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    ...
```
or this:
```yaml
byodc:
  config:
    ...
    env:
    - name: DD_AGENT_HOSTNAME
      value: somevalue
    ...
```

FYI We have also made the repo containing the chart public https://github.com/fiskaltrust/helm-charts and will be accepting contributions there :)
